---
upgrade:
  - The upgrade process will backup and re-configure the /etc/openstack_deploy
    directory. This includes inserting new environment details, updating
    changed variable names, and generating newly added secrets.
