---

- name: Install midonet agent on compute hosts
  hosts: compute_hosts
  max_fail_percentage: 0
  user: root
  roles:
    - midonet-agent
  vars:
    zookeeper_hosts: '{{ groups["zookeeper_all"] }}'
    midonet_password: '{{ midonet_api_password }}'
    cluster_hostname: ³# Midonet cluster api goes here.


- name: Install midonet agent on gateway hosts
  hosts: gateway_hosts
  max_fail_percentage: 0
  user: root
  roles:
    - midonet-agent
  vars:
    zookeeper_hosts: '{{ groups["zookeeper_all"] }}'
    midonet_password: '{{ midonet_api_password }}'
    cluster_hostname: ³# Midonet cluster api goes here.
